### ISSUE TITLE
Tanda Petik Ganda pada XML Blogger di Folder `/dist`

### ISSUE THREAD

**Issue by taufik-nurrohman** [bloggerpack/bloggerpack#30]
Ada alasan khusus kenapa memakai tanda petik ganda di atribut XML Blogger di `/dist` mas? Kalau disimpan melalui dasbor Blogger biasanya langsung dikonversi ke petik tunggal, jadi Saya pikir yang standar itu petik tunggal. Selain itu, petik ganda sudah biasa dipakai sebagai indikator _string_ di dalam tema. Misal:

``` .xml
<b:class expr:name='"foo-" + data:bar'/>
```
Kalau pakai petik ganda jadi begini?

``` .xml
<b:class expr:name="'foo-' + data:bar"/>
```

Atau itu karena dibuat otomatis oleh linter-nya kah?

**Comment by igoynawamreh** [comment]
@taufik-nurrohman itu disebabkan oleh prettier. Susah untuk menemukan plugin yang cocok untuk sintaks XML blogger.

Ini sebenarnya sudah masuk daftar todo yang harus diperbaiki mas, tapi masih saya biarkan karena masih bisa diterima oleh mesin Blogger, malah seperti yang mas bilang mesin blogger langsung memperbaikinya.

Solusinya bisa pakai `regex`. Bisa buatkan bentuk `regex` nya?

Content:

```html
<tag attr="value" attr2='value'   /> # target
<tag2 attr='value' attr2="value"/>    # target
<tag3 attr='value' attr2='value'/>    # skip
<tag4 attr='"string"' + data'     />     # skip
<tag5 attr="'string'" + data" />        # target 
```
Setelah di-replace:

```html
<tag attr='value' attr2='value'   /> # target
<tag2 attr='value' attr2='value'/>    # target
<tag3 attr='value' attr2='value'/>    # skip
<tag4 attr='"string"' + data'     />     # skip
<tag5 attr='"string"' + data' />        # target 
```

**Comment by taufik-nurrohman** [comment]
Oke. Nanti tak kabari lagi.

**Comment by igoynawamreh** [comment]
> Intinya kalau untuk kasus sudah ada tanda petik ganda di dalam itu dia normal-normal saja kan, langsung respon sebagai tanda petik tunggal?

Betul mas. Untuk yang tidak ada tanda petik ganda di dalamnya terkadang dia pakai petik ganda.

**Comment by taufik-nurrohman** [comment]
``` .js
function toSingleQuotedAttributes(str) {
    return str.replace(/<[^>]+>/g, m0 => {
        if (-1 !== m0.indexOf('="')) {
            m0 = m0.replace(/="((?:\\\\.|[^"])*)"/g, (m0, m1) => {
                return "='" + m1.replace(/'/g, '"') + "'";
            });
        }
        return m0;
    });
}
```

``` .js
console.log(toSingleQuotedAttributes(`<foo bar="baz">
<foo bar="baz 'qux'">

"foo" 'bar'
"foo 'bar'" 'bar "baz"'

<foo bar='baz'>
<foo bar='baz "qux"'>`));
```

**Comment by taufik-nurrohman** [comment]
Masukin Saya ke daftar kontributor mas! HEHEHEHEHEHE.

**Comment by taufik-nurrohman** [comment]
BTW, itu opsi `singleQuote` gunanya untuk apa?

**Comment by igoynawamreh** [comment]
> Masukin Saya ke daftar kontributor mas! HEHEHEHEHEHE.

Sure. Nanti saya ubah role-nya ke maintainer.

> BTW, itu opsi singleQuote gunanya untuk apa?

Itu dia, prettier tidak mengenal sintaks blogger. Sebenarnya ada plugin prettier untuk XML, tapi tetap saja tidak berpengaruh kalau di sintaks blogger.

**Comment by igoynawamreh** [comment]
Ada satu masalah:

```html
expr:onsubmit='"window.open(\"https://feedburner.google.com/fb/a/mailverify?uri=" + data:feedPath + "\", \"popupwindow\", \"scrollbars=yes,width=550,height=520\"); return true"'
```

Replaced to:

```html
expr:onsubmit='"window.open(\"https://feedburner.google.com/fb/a/mailverify?uri=' + data:feedPath + '\", \"popupwindow\", \"scrollbars=yes,width=550,height=520\"); return true"'
```

- `mailverify?uri="` => `mailverify?uri='`
- `data:feedPath + "\"` => `data:feedPath + '\"`

**Comment by taufik-nurrohman** [comment]
Sepertinya itu karena terdeteksi pola `="` tapi ada di dalam _string_, bukan pola dari nilai atribut.

Error kalau begini:

~~~ .js
<foo bar='baz="qux"'
~~~

Nanti tak perbaiki.

**Comment by igoynawamreh** [comment]
Pastikan code HTML di dalam JS tidak ter-replace juga mas @taufik-nurrohman.

```html
<script>
var html = '<div class=""></div>';
</script>
```

**Comment by taufik-nurrohman** [comment]
``` .html
<script>

const STR_DOUBLE = `(")((?:\\\\.|[^"])*)(")`;
const STR_SINGLE = `(')((?:\\\\.|[^'])*)(')`;
const STR = '(?:' + STR_DOUBLE + '|' + STR_SINGLE + ')';

const IGNORE = ['script', 'style', 'textarea'];
const IGNORE_REGEX = IGNORE.map(
    el => '(<' + el + '(?:\\s[^>]*)?>)([\\s\\S]*?)(<\\/' + el + '>)'
).join('|');

function toSingleQuotedAttributes(str) {
    return str.replace(new RegExp(IGNORE_REGEX + '|<(' + STR + '|[^>])+>', 'g'), m0 => {
        if ((new RegExp('^(' + IGNORE_REGEX + ')$').test(m0))) {
            // Skip, but convert attribute in the opening tag as well!
            let tagStart = new RegExp('^<(' + IGNORE.join('|') + ')(\\s(?:' + STR + '|[^>])*)?>', 'g');
            return m0.replace(tagStart, m0 => toSingleQuotedAttributes(m0));
        }
        return m0.replace(new RegExp('=' + STR, 'g'), m0 => {
            if (0 === m0.indexOf("='")) {
                return m0; // Skip!
            }
            return m0.replace(new RegExp(STR_DOUBLE, 'g'), (m0, quoteStart, quoteValue, quoteEnd) => {
                return "'" + quoteValue.replace(/'/g, '"') + "'";
            });
        });
    });
}

console.log(toSingleQuotedAttributes(`
<foo bar="baz">
<foo bar='baz'>

<foo bar="baz 'qux'">
<foo bar='baz "qux"'>

"foo" bar
'foo' bar

"foo 'bar'" baz
'foo "bar"' baz

<foo bar="baz > 0">
<foo bar="baz < 0">

<foo bar='baz > 0'>
<foo bar='baz < 0'>

<foo bar="'baz' + qux">
<foo bar='"baz" + qux'>

<foo bar="'baz=\\"qux\\"' + qux">
<foo bar='"baz=\\'qux\\'" + qux'>

<style>
  <foo bar="baz">
</style>

<style foo="bar > 0">
  <foo bar="baz">
</style>
`));

</script>
```

Mau tak jadikan [paket NPM](https://github.com/taufik-nurrohman/quote) kalau berhasil nanti.

**Comment by igoynawamreh** [comment]
Boleh mas, lebih bagus kalau dibikin paket NPM, bermanfaat untuk yang lainnya juga.

**Comment by taufik-nurrohman** [comment]
Coba mas! &rarr; https://www.npmjs.com/package/@taufik-nurrohman/quote :fire:

``` .js
import {HTML} from '@taufik-nurrohman/quote';

console.log(HTML.singleQuote(res));
```

**Comment by igoynawamreh** [comment]
Bisa gak dibikin bisa pakai `require`:

```js
const {HTML} = require('@taufik-nurrohman/quote');
```

Sebenarnya bisa pakai `import` dengan cara menambahkan `"type": "module"` di `package.json`. Tapi nanti kita harus ubah semuanya, sedangkan kebanyakan paket pakai `require`.

[Lihat ini mas](https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module).

**Comment by taufik-nurrohman** [comment]
Kalau begini bisa nggak mas?

https://medium.com/@dandv/publishing-native-es-modules-with-node-v8-5-0-730736e0f612

Saya nggak keberatan bikin duplikat CJS, cuma Saya pingin MJS bersih dari token `exports`, `module`, dan `require`.
